### ISSUE TITLE
Bug: Can't load images from other drives

### ISSUE THREAD

**Issue by greencloversguy** [deepnight/led#108]
When I try to open an image file for the tileset image, if an image is not in the same drive as where LEd installed, then I get an error saying "ERROR: Couldn't read image data". If I copy the image to the same drive, then it can load it. 

The drive it's installed to is C and the drive the images are in is the D drive. 

If you need anymore info, please let me know.

**Comment by deepnight** [comment]
Hmm I see the issue here: it's definitely related to my `dn.FilePath` class which doesn't properly support different drive paths.

I will fix that.
