### ISSUE TITLE
Display tileId on tile hover (or on tile select)

### ISSUE THREAD

**Issue by RPGillespie6** [deepnight/led#115]
It would be nice if the `tileId` of a given tile could be displayed in the status area of L-Ed (bottom right corner), something like:

![image](https://user-images.githubusercontent.com/9853156/94444708-9b673b00-0174-11eb-99ff-2f3aeb01b82b.png)

Otherwise, it's hard to tell which tile a given tileId corresponds to without manually counting into tileset with `__tileX` and `__tileY`. In Tiled, it is displayed whenever you click a tile in the tileset under Tile properties:

![image](https://user-images.githubusercontent.com/9853156/94445542-8d65ea00-0175-11eb-902e-ed35d2934cc5.png)

**Comment by deepnight** [comment]
Good idea :) Would definitely be useful!

**Comment by deepnight** [comment]
Done, will be there in next update.
