### ISSUE TITLE
Add coordId to each tile in tiles [json enhancement for import]

### ISSUE THREAD

**Issue by Zelberor** [deepnight/led#120]
As far as I have understood it, a tile in the tiles-array can actually have a position that is different to the coordId (when using stamps).
For the LEd->Unity importer that I am currently working on this becomes a problem, as each tile of a stamp gets put on the same position in the Tilemap.
(Unity does not support pixel coordinates, only grid coordinates for tilemaps. So using a coordId makes more sense than __x and __y).
For easier importing and correct support of stamps in my importer it would be very useful, if  each tile in an autotile layer had a coordId:

```
> "autoTiles": [
> 	{
>    		"ruleId": 101,
> 		"results": [ {
> 			"coordId": 90,
> 			"tiles": [
> 				{ "tileId": 169, "__x": 0, "__y": -8, "__srcX": 8, "__srcY": 112 }, <--- add matching coordId
> 				{ "tileId": 181, "__x": 0, "__y": 0, "__srcX": 8, "__srcY": 120 } <--- add matching coordId
> 			],
> 			"flips": 0
> 		} ]
> 	}
> ]
```
Thanks for the great tool btw.

**Comment by deepnight** [comment]
Actually, because of customizable pivot point, a Rule can add a stamp between grid coordinates, like here:

![image](https://user-images.githubusercontent.com/1671695/94823597-522d1a80-0404-11eb-8f88-231c14c6744a.png)

So the tile coordId would not work in such a case 🤔

**Comment by Zelberor** [comment]
Ah ok... guess I need to find a workaround then.
