### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by botolo78** [deepnight/led#122]
Hi, I'm not a coder but I like to learn new skills and in the last weeks I was enjoying some light "game development". Please take this for what it is, only the opinion of a tourist of this world :)

First of all LEd is a beautiful piece of software. The UI is untraditional, but that's not an issue. Overall I liked it very much and it's really user friendly. My criticism comes from a noob prospective.

You clearly know your stuff, I was reading and checking on Haxe, Heaps and LEd and I was very excited about all, but the learning curve right now is clearly targeting someone with a more than decent skillset.
I'm not sure if you are really interested in making the stack increase in popularity, but I think the noobs are a really good starting point for that. I also know you don't have time to write extended tutorials for everything, so these are my 2 cents:

GameBase is already available and there are 2 small tutorials on the website.
Try to rewrite them, including LEd, in something like

- Let's create a GameBase copy
- Now let's create a basic collision routine to limit player movement inside the level
- Player is colliding with borders, let's apply gravity, friction and acceleration
- Next we'll learn how to jump
- With the basics there, let's load and draw a basic LEd level, using collisions
- Finally let's replace our square player with a Sprite, and maybe at least one idle animation

Having something working in my opinion would help to spread word of the awesome job you did.

Just a few final words to conclude :)

- Names. Heaps and LEd are not "google search" friendly. 
- Make LEd usable from something like Godot (even in a PRO version that I personally would buy) will shine a spotlight onto this software

That's all, thanks ;)

**Comment by deepnight** [comment]
I agree with pretty much all your points here ;)

Proper docs/tutorials are the base requirement for any app today, and the learning curve should be as easy as possible.

I definitely plan to adapt GameBase to properly support LEd data, and update my tutorials accordingly. It's on the way, as soon as I've enough time 😅

**Comment by deepnight** [comment]
**GameBase** was updated to support LEd out-of-the-box in the `advancedBase` branch: 

https://github.com/deepnight/gameBase/tree/advancedBase

**Comment by botolo78** [comment]
I'm playing around with your LD47 and is very helpful to see a real game working with ldtk. Very impressed 😲
