### ISSUE TITLE
An array of entities return null if there is no entity of this kind in the level.

### ISSUE THREAD

**Issue by Tipyx** [deepnight/led#131]
I created a level with an entity "EntityType", but I didn't put any of them in my level.
If I loop on the array of these entities in my code, like this
```
for (et in lvlData.l_Entities.all_EntityType) {
	new en.EntityType(et.cx, et.cy);
}
```
I get a throw 'cause "all_EntityType" is null.
It never should be null, but empty instead.

**Comment by deepnight** [comment]
Fixed in latest git version (requires LEd 0.4.0)
