### ISSUE TITLE
Undo does not work for rule changes

### ISSUE THREAD

**Issue by SecretPocketCat** [deepnight/led#144]
_Expected behaviour:_  
changing a rule and then un/redoing should undo that rule change.

_Actual behaviour:_  
No undo

**Comment by deepnight** [comment]
Yes, that's a known issue, but it would be really hard to fix it: rules are part of the project *Definitions*, and they affect the whole project (ie. all levels). Having undo/redo support for rules would mean to re-invalidate all levels, which could lead to performance issues on larger projects.

Anyway, undo/redo will need some rework at some point, but that's a for a future update :)

**Comment by deepnight** [comment]
Opened #151
