### ISSUE TITLE
Metadata for autolayer rules

### ISSUE THREAD

**Issue by TheNeikos** [deepnight/led#152]
I'm using the autolayer feature to create 'grass decorations':
![image](https://user-images.githubusercontent.com/1631166/95473595-cbcc8780-0973-11eb-9991-d313ebc5b8f5.png), 
and I'd like to render them _above_ the player. But since they share the same tileid as the actual 'solid' grass I cannot differentiate between them. I could see multiple ways this might be helped:

- A flag 'toFront/toBack' or so. This is not so ideal, as it presumes that the editor is only ever used for sidescrollers etc.. but that's not true IIUC
- Custom data that can be set project-wide similar to entites, where a autolayer 'group'/rule has to pick a value from it. In my case I'd make it an enum with 'Background/Solid/Foreground' depending on what I'd need it to do.
- Custom data per autolayer group/tile, every group/tile can have the same or different values.

I'd also be willing to help implement this if you accept pull-requests!

**Comment by deepnight** [comment]
The current way to do that is to create a *separate* `AutoLayer` (a pure one, not an `IntGrid`) that uses the IntGrid where collisions are. This separate layer can hold any "front" object easily.

Then, in your game, just render the layer above player.

**Comment by deepnight** [comment]
There is a demo of this in the **Typical 2d platformer** sample:

`bg_textures` uses `collisions` as source for its data.

![image](https://user-images.githubusercontent.com/1671695/95481014-d2b3c400-098c-11eb-8709-6dad0e98b553.png)

**Comment by TheNeikos** [comment]
![image](https://user-images.githubusercontent.com/1631166/95498314-23c6b680-0993-11eb-9cf7-f5e705477016.png)

Ah! That works like a charm! I guess that covers my use case then. I didn't know you could apply autolayers from other intlayers. Thanks!
