### ISSUE TITLE
Save keyboard shortcut on macOS should be command + s

### ISSUE THREAD

**Issue by fabtjar** [deepnight/led#154]
Currently saving on the macOS version is control + s. All other apps I've used on this OS is command + s.

I'm assuming other keyboard shortcuts are using control instead of command too.

**Comment by fabtjar** [comment]
Hmm, maybe something else is up. command + s saves selection in the level edit screen. and control + s saves the project.

**Comment by deepnight** [comment]
I'll see if I can fix that :)

**Comment by deepnight** [comment]
I pushed a fix that will be released with **0.4.0** (maybe today or next week). I don't own a Mac so I can't test the change :)

**Comment by fabtjar** [comment]
Don't think it's fixed. Still the same as last time.
