### ISSUE TITLE
Rules panel undocks and stuck

### ISSUE THREAD

**Issue by capttheo** [deepnight/led#173]
Hello, firstly thank you for working on this amazing tool.
Several times I've encountered strange behavior and couldn't figure way out.
After some manipulation, may be mouse dragging, panel is pops out and stucks, obscuring editing field.
I've tried, but no avail, have to close app and reopen.
I have uploaded video where you can see it's possible to open even the same panel over stuck instance.
https://drive.google.com/file/d/11I5jK0DdJRlN3dTjlXorPbia2gmluc7B/view?usp=sharing
I'm using dev 0.4.0 version, from day ago.

**Comment by deepnight** [comment]
Hi!
Because you're using latest GIT build, you might encounter some crashes or exceptions. I recommended building the app with the `-debug` flag, as it will show any exception in the Dev console (CTRL-SHIFT-I).

If the error happens again, please check the console panel and report me any anomaly 👍

**Comment by deepnight** [comment]
Related #174

**Comment by deepnight** [comment]
Do you still have this bug?

**Comment by deepnight** [comment]
Feel free to re-open the issue if you still get a crash with 0.4.1 version
