### ISSUE TITLE
Options to duplicate and disable an existing rule

### ISSUE THREAD

**Issue by profexorgeek** [deepnight/led#183]
This is two related feature requests in one.

I'm testing with a top-down tileset that has walls that are three tiles high (including top). There are a lot of complex cases for rules and it's sometimes hard to tell which rule is breaking things. **The ability to disable a rule without deleting it** would be extremely useful.

Additionally, I frequently had to create rules that were very similar but had some small difference. **The ability to clone/duplicate an existing rule** would be useful for creating similar rules for different transition types.

Here's a screenshot of the tileset/ruleset I was testing for context:
![image](https://user-images.githubusercontent.com/711100/96885335-b8bfba00-143f-11eb-8057-932142648626.png)

Thanks for your amazing work on this tool, it has the potential to cut level design time to a fraction of what it usually takes.

**Comment by deepnight** [comment]
You can disable rules by clicking the Eye icon near it:

![image](https://user-images.githubusercontent.com/1671695/96886265-b7b07c00-1483-11eb-84c7-122b013a449a.png)

Note: disabling a rule will also disable it on Json export: what you see if what you get in the actual Json.

The duplicate feature is coming tomorrow with 0.4.0 update (among many other things) :) See [Git changelog](https://github.com/deepnight/led/blob/master/CHANGELOG.md).

**Comment by profexorgeek** [comment]
How did I miss that!? You are awesome, thank you!

**Comment by deepnight** [comment]
Duplication is now available in 0.4.x :)
