### ISSUE TITLE
Add Save Changes feature on file close attempts

### ISSUE THREAD

**Issue by zshoals** [deepnight/led#45]
Closing a file that has not been saved already gives you a prompt to ignore map changes or to cancel the close attempt. It seems strange to me that direct Save functionality is not in this prompt as well.

**Comment by deepnight** [comment]
I actually _had_ a Save button here, but it was slightly more confusing to have 3 buttons instead of 2. I will give that another try :)

**Comment by deepnight** [comment]
I went for a more straightforward prompt question. Works better imho: 

![image](https://user-images.githubusercontent.com/1671695/91188887-18287480-e6f2-11ea-8f5d-83c3d7654be9.png)
