### ISSUE TITLE
Input Lag

### ISSUE THREAD

**Issue by BurgerBob** [deepnight/led#804]
There is roughly 300ms of input lag between the position of the mouse cursor and the results in the editor.
 
It seems to be unrelated to frame rate, because it exists on even very simple worlds, but it worsens when the editor has performance problems.

My guess is that it is linked to the way the editor handles double (triple ?) buffering, because you can see intermediate positions of the past when you move the mouse cursor. It could also be something very simple like reading the position of the mouse at a different time in the rendering loop.

I think it would dramatically improve the feeling of using the editor if this issue was solved.

**Comment by deepnight** [comment]
That's a huge lag 😮
I couldn't reproduce that on my setup. Could you please provide more details?

 - your OS and system,
 - your setup
 - your GPU

**Comment by BurgerBob** [comment]
Windows 10
11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, Intel(R) Iris(R) Xe Graphics
A 2560x1600 screen plugged in on a laptop.

A lead: it seems that input lags only appear when the width of the ldtk window is more than 2048. 
Maybe we hit a limit on integrated graphic cards ?

**Comment by deepnight** [comment]
Good news :) Feel free to reopen the issue if you notice some continuous lag, even after reboot.
