### ISSUE TITLE
Mouse is stuck clicked 

### ISSUE THREAD

**Issue by eguneys** [deepnight/led#83]
I click and draw, when I release the mouse it stays clicked and continues drawing. If I press ALT+Click, mouse releases. If I click again it is stuck again. This happens on other tools as well.

**Comment by deepnight** [comment]
Do you have any specific configuration, like using a trackpad or something similar?

**Comment by eguneys** [comment]
No, just a USB wireless mouse.

**Comment by deepnight** [comment]
I can't reproduce your issue, could you please provide extra informations about your setup? OS version, mouse model etc. 🤔

**Comment by eguneys** [comment]
I can't reproduce it either, I will provide more details if I encounter this issue again.
