### ISSUE TITLE
Folder contents obliterated when simple exporting

### ISSUE THREAD

**Issue by SitKneesweak** [deepnight/led#914]
When you simple export everything in the level folder gets wiped before being recreated which is inconvenient if you store other files in there

**Comment by deepnight** [comment]
Hi,
As you mentioned, these folders are created and maintained by the app as you save your project. By definition, it's not a good idea to put important personal stuff in here.

**Comment by SitKneesweak** [comment]
I run shell scripts based on the contents of the folder which have to be run from that specific folder. I’ll look into alternatives, thanks for getting back.
