### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by LiamDawe** [deepnight/led#97]
Hi, just a quick one. It needed one small fix to get it to _start_ compiling on Arch Linux (and probably all others?)

In the /app/package.json file it has this one line 10
> "compile": "cd..  &&  haxe main.hxml  &&  haxe renderer.hxml",

That doesn't work, changing it to this does:

> "compile": "cd ../  &&  haxe main.hxml  &&  haxe renderer.hxml",

You're also missing "castle" in your haxe dependency list. So it needs adding please :+1: 

After that was sorted, it then fails on this point:

> Converting /home/liam/Downloads/led-0.2.0-beta/res/fonts/minecraftiaOutline.fnt
> src.renderer/Const.hx:35: characters 35-49 : Warning : Couldn't write app/build/release-notes.md

**Comment by deepnight** [comment]
Could you please check if the commit fixes your issue?

**Comment by LiamDawe** [comment]
Afraid not, however, creating the build folder inside /app did make it work. So it needs something to check if the build directory exists and create it if not.

Once that's done, we get further but still not there yet.

> [liam@liam-pc app]$ npm run compile
> 
> > led@0.2.1-beta compile /home/liam/Downloads/led-master/app
> > cd ../  &&  haxe main.hxml  &&  haxe renderer.hxml
> 
> src.renderer/App.hx:24: characters 7-18 : dn.Log has no field logFilePath
> src.renderer/App.hx:28: characters 7-17 : dn.Log has no field emptyEntry
> src.renderer/App.hx:305: characters 8-19 : dn.Log has no field flushToFile
> src.renderer/App.hx:166: characters 9-17 : dn.Log has no field printAll
> src.renderer/App.hx:314: characters 8-19 : dn.Log has no field flushToFile
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! led@0.2.1-beta compile: `cd ../  &&  haxe main.hxml  &&  haxe renderer.hxml`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the led@0.2.1-beta compile script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm WARN Local package.json exists, but node_modules missing, did you mean to install?
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/liam/.npm/_logs/2020-09-25T11_25_10_805Z-debug.log

Full log is here: https://gist.github.com/LiamDawe/3ec683b56acc1ecd34a8cf1f5d84ce45

**Comment by deepnight** [comment]
You should update the deepnightLibs from git:

`haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git`

For future updates, just run:

`haxelib update deepnightLibs`

**Comment by LiamDawe** [comment]
Interesting, okay, after running haxelib update deepnightLibs it gave no more errors.

> [liam@liam-pc app]$ npm run compile

> led@0.2.1-beta compile /home/liam/Downloads/led-master/app
> cd ../  &&  haxe main.hxml  &&  haxe renderer.hxml

However, the build folder still only has the readme file in it and nothing else?

**Comment by deepnight** [comment]
Yes, the `release_notes.md` file is only used for GitHub Releases uploads: its an extraction of the `CHANGELOG.md` containing only the latest changes. 

For now, the build folder only has that, but in the future, I'll add some app icons (#55)

**Comment by LiamDawe** [comment]
Ah right okay, how do I actually run it to test now then? :) (I'm not actually familiar with how Haxe does things)

**Comment by deepnight** [comment]
As soon as you compiled it, you should have a `main.js` in app/, and a `renderer.js` in app/js/.

If they are there, you should be able to run electron from the app/ folder:

```
npm run start
```

**Comment by LiamDawe** [comment]
Nope, those files don't seem to exist, nor does the js folder.

**Comment by deepnight** [comment]
My bad! It's `app/assets/main.js` and `app/assets/js/renderer.js`

**Comment by LiamDawe** [comment]
Ah good, not me doing something wrong then like I thought :+1: 

Well, it loads and gives me a blank UI along with an error https://i.imgur.com/S5NJbmW.png - I do have electron-updater installed through npm though.

**Comment by deepnight** [comment]
Not sure it's related, but I updated the "Compiling" instructions of the README:

**Comment by deepnight** [comment]
Also, if you run this from the `app` folder:

```
npm list --depth=0
```

Do you get these?

```
led@0.2.1-beta C:\projects\led-source-test\led\app
+-- electron@10.1.2
+-- electron-builder@22.8.1
+-- electron-updater@4.3.5
`-- sortablejs@1.12.0
```

**Comment by LiamDawe** [comment]
Looking good now with the new instructions, it runs and I get the proper UI. Still need to make the build folder manually but that's a minor point.

Great job :)

**Comment by deepnight** [comment]
I'll fix the build folder check :)
